const colors = require('tailwindcss/colors');

const color = {
  'primary-default': colors.cyan[700],
  'primary-deep': colors.cyan[800],
  'primary-light': colors.cyan[50],
  'danger-default': colors.red[600],
  'danger-deep': colors.red[700],
  'danger-light': colors.red[100],
  'object-default': colors.gray[900],
  'object-secondary': colors.gray[700],
  'object-middle': colors.gray[500],
  'object-light': colors.gray[400],
  'object-empty': colors.gray[300],
  'object-white': colors.white,
  'border-default': colors.gray[300],
  'background-black': colors.gray[900],
  'background-dark': colors.gray[100],
  'background-light': colors.gray[50],
  'background-white': colors.white,
  'sub-red-default': colors.red[600],
  'sub-red-light': colors.red[100],
  'sub-orange-default': colors.orange[600],
  'sub-orange-light': colors.orange[100],
  'sub-yellow-default': colors.yellow[600],
  'sub-yellow-light': colors.yellow[100],
  'sub-green-default': colors.green[600],
  'sub-green-light': colors.green[100],
  'sub-blue-default': colors.blue[600],
  'sub-blue-light': colors.blue[100],
  'sub-indigo-default': colors.indigo[600],
  'sub-indigo-light': colors.indigo[100],
  'sub-purple-default': colors.purple[600],
  'sub-purple-light': colors.purple[100],
  'sub-pink-default': colors.pink[600],
  'sub-pink-light': colors.pink[100],
};

/** @type {import('@types/tailwindcss/tailwind-config').TailwindConfig} */
const config = {
  mode: 'jit',
  purge: ['./src/**/*.{js,ts,jsx,tsx}'],
  darkMode: false, // or 'media' or 'class'
  theme: {
    borderColor: (theme) => ({
      ...theme('colors'),
      color,
    }),
    ringColor: (theme) => ({
      ...theme('colors'),
      color,
    }),
    fontSize: {
      xs: '12px',
      sm: '14px',
      base: '16px',
      lg: '18px',
      xl: '20px',
      '2xl': '24px',
      '3xl': '30px',
      '4xl': '36px',
      '5xl': '48px',
      '6xl': '60px',
      '7xl': '72px',
    },
    spacing: {
      px: '1px',
      0: '0',
      0.5: '2px',
      1: '4px',
      1.5: '6px',
      2: '8px',
      2.5: '10px',
      3: '12px',
      3.5: '14px',
      4: '16px',
      5: '20px',
      6: '24px',
      7: '28px',
      8: '32px',
      9: '36px',
      10: '40px',
      11: '44px',
      12: '48px',
      14: '56px',
      16: '64px',
      20: '80px',
      24: '96px',
      28: '112px',
      32: '128px',
      36: '144px',
      40: '160px',
      44: '176px',
      48: '192px',
      52: '208px',
      56: '224px',
      60: '240px',
      64: '256px',
      72: '288px',
      80: '320px',
      96: '384px',
    },
    extend: {
      colors: {
        color,
      },
      lineHeight: {
        3: '12px',
        4: '16px',
        5: '20px',
        6: '24px',
        7: '28px',
        8: '32px',
        9: '36px',
        10: '40px',
      },
    },
    borderRadius: {
      none: '0px',
      sm: `${16 * 0.125}px`,
      DEFAULT: `${16 * 0.25}px`,
      md: `${16 * 0.375}px`,
      lg: `${16 * 0.5}px`,
      xl: `${16 * 0.75}px`,
      '2xl': `${16 * 1}px`,
      '3xl': `${16 * 1.5}px`,
      full: '9999px',
    },
  },
  variants: {
    extend: {},
  },
  plugins: [require('@tailwindcss/forms'), require('@tailwindcss/line-clamp')],
};

module.exports = config;
