/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as contracts from "./contracts";
export type { contracts };
export * as factories from "./factories";
export type { Wave } from "./contracts/Wave";
export { Wave__factory } from "./factories/contracts/Wave__factory";
